version: "2.4"

services:
  app:
    build: .
    command: 'sh -c "echo ''Starting app...'' && php -S 0.0.0.0:8080 -t public"'
    image: felipechagas/sms_sender:latest-slim
    ports:
      - 8080:8080
    networks:
      - net
    volumes:
      - ./:/var/www/html:delegated
      - ./.env:/var/www/html/.env:delegated,ro
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-sms_sender}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mysql}
    ports:
      - 3306:3306
    networks:
      - net

networks:
  net:
